Bugfix/7/websocket-keepalive-heartbeat
rezonence/full-stack-challenge pull request #8
Opened 2022-07-19 22:52 UTC by dsfx3d

- Add a heartbeat broadcast on backend to send a dummy messege to all
  connected clients before the websocket connect times out.
- Handle the dummy message in frontend
- Add abstraction to broadcasting from Api Gateway

Resolves: #7

2022-07-20 10:18 UTC, jabrythehutt requested changes

2022-07-20 10:23 UTC, jabrythehutt commented
Better to avoid folder/class names like `utils` since it generally encourages a dumping ground - let's think of a name that reflects exactly what useful things any new classes actually do

2022-07-20 10:34 UTC, jabrythehutt commented on src/polls/PollBroadcaster.ts
> +    this.pollUpdates = this.toUpdates(items)
Mutation of the `pollUpdates` field could cause problems - much better to pass in "updates" as an argument

2022-07-20 10:37 UTC, dsfx3d commented on src/utils/Broadcaster.ts
> +  getBroadcastRequest (connectionId: string): Promise<void | void[]> {
I just added abstraction in order to ignore redundant code. Yeah I understand we can use a better name for the method it but all of the implementation classes will have to implement this method because this is where you put the data you are supposed to broadcast.

Yet again the abstraction is because in both the places we are broadcasting to all clients the only difference being the data to be broadcasted.

2022-07-20 10:40 UTC, dsfx3d commented on src/polls/PollBroadcaster.ts
> +    this.pollUpdates = this.toUpdates(items)
we can pass it down through the `broadcast` like it was already being done prior to the changes I made. That'll make it more stateless and basically the same as it was before.

2022-07-20 10:43 UTC, dsfx3d commented on src/websocket/DynamoWebsocketApi.ts
> +      keepAliveBroadcaster.addToRolePolicy(new PolicyStatement({
we can add a policy management class, do you have some other ideas?

2022-07-20 11:18 UTC, dsfx3d commented on src/utils/broadcaster.t.ts
> +  getBroadcastRequest(connectionId: string): Promise<void | void[]>
I'll work on a better name

2022-07-20 18:42 UTC, dsfx3d commented on src/websocket/DynamoWebsocketApi.ts
> +      keepAliveBroadcaster.addToRolePolicy(new PolicyStatement({
Added SSOT for WebSocket API resource ARN

2022-07-21 08:54 UTC, jabrythehutt requested changes

2022-07-21 08:54 UTC, jabrythehutt commented on src/websocket/Broadcaster.ts
> +  protected BROADCAST_BATCH_SIZE = 10
No need to use uppercase here, let's stick to camelCase, also better to pass this in as a constructor argument

2022-07-21 08:54 UTC, jabrythehutt commented on src/websocket/Broadcaster.ts
> +export class WebsocketBroadcaster<T> {
Let's keep the class name consistent with the file name

2022-07-21 08:54 UTC, jabrythehutt commented on src/websocket/keepalive/handler.ts
> +  await broadcaster.broadcast({})
I thought the frontend was always expecting to get a `PollUpdates[]`, why are we pushing a different type here?

2022-07-21 08:54 UTC, jabrythehutt commented on src/websocket/Broadcaster.ts
> +  async broadcastToConnection (connectionId: string, payload: T) {
The implementation assumes that the `payload` argument is going to be an array - makes more sense to make this a `T[]`

2022-07-21 09:04 UTC, dsfx3d commented on src/websocket/keepalive/handler.ts
> +  await broadcaster.broadcast({})
The `WebsocketBroadcaster` will always broadcast an array ([here](https://github.com/rezonence/full-stack-challenge/blob/419d14ac5848a6e90c7f8a40b51738b5c67a3c8c/src/websocket/Broadcaster.ts#L30)) but the `broadcast` method can accept both an array or a single object/variable.

The `broadcast` method will `concat` it into an array before broadcasting

2022-07-21 09:05 UTC, dsfx3d commented on src/websocket/Broadcaster.ts
> +  async broadcastToConnection (connectionId: string, payload: T) {
it's just `T` so we can broadcast both arrays and single values

2022-07-21 09:06 UTC, jabrythehutt commented on src/websocket/keepalive/handler.ts
> +  await broadcaster.broadcast({})
I think it makes more sense to broadcast an empty array than an object that doesn't conform to the `PollUpdates` interface

2022-07-21 09:07 UTC, dsfx3d commented on src/websocket/Broadcaster.ts
> +  protected BROADCAST_BATCH_SIZE = 10
by convention in my own sense I use uppercase/snakecase to represent constant values. do you have some convention for the same.
We should follow a style guide as well

2022-07-21 09:11 UTC, dsfx3d commented on src/websocket/keepalive/handler.ts
> +  await broadcaster.broadcast({})
ok, makes sense

2022-07-21 09:53 UTC, dsfx3d commented on src/websocket/keepalive/handler.ts
> +  await broadcaster.broadcast({})
When we pass an array of `PollUpdates` to the broadcaster, essentially we are passing down an array of messages to be broadcasted. If we pass an empty array it means there are no messages to be broadcasted. To broadcast an empty array we'll have to check inside the broadcaster class if the payload is an empty array and then add explicit code to handle that case.
Do we want to go down this path?

2022-07-21 13:42 UTC, jabrythehutt approved these changes

2022-07-21 13:43 UTC, merged